---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secret
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgBD6vv3smG/7yd0HJ/7WyO7Ax2W7uV+kPvjMjUCC1yH8iXSVUDHoiIHOmqUf9AsEXQ0IPioHdxuRfYKUJ69yjgAnBHgPGVfeedhzQJwVlPk4uCHl2bJUwk6mIoQnA3biF8PRM2/Wof3ZnSXCF6xi6hPbE1cMojZ02eVoAfyVsCJafXyTa3r9KXhVBDz8ViFp5sHZiL3XMtV4/OGCkPnDAnptJ71iy2moMpowPfXX970g2dOT7bk7m6oX1CoHNV5xqVaG9POYzLDR8C7XiLEbkp4pDblFpBqHJkb+xJ+aLzJy3Ixsdvo6TsBfRLzw8DnPiqanUcQcMHitSXJ1Yn0+uABQRZYEcMS8Tlzj8BoZLk1phZCjLBt8mN3xpYDcJ+mKqB7cQGh/nDAiNohj0zDITVYvk3FXKAWGKbOVz8/YA/QQAgSrwBDUjkWLtSJa3MB36IpZhkuwElU0K8oNyQJmwmMTRgR+87TdCZSDjMM3XIqc8YP4R3+AJE6PZ3sVFEfP7EmNNLHUvYEQl2VOhIPjgTcfojAoHZn+YNPfx+hDc0LmMYFcizDBMAaQgEfBNzNHbW3+ymo+K0klcUE1S5zVgN7Ayp17cnU/GyyUI4Zc34jgWvzxwGwMj/67Ie9cF3rlwrrkKg4qJ+ndkuvyVyiEJI/FAgYkZ8uLF7hxQEUDCyAqjQjlMcfPFSefOqHcaWAInZ4B197C/gR62DcOrVmElHLDCbIz4VYOm1ZJRGimbF7tnoC1L877BpXhuvJ5Q==
    JWT_SECRET: AgBdIoJJdhFC2RrHMUgLgx8j785n5VjkZ1MgeoyMDEM+atnL3l5MkJ3vA7fptAUtpz3k6MLnldnfhuovqVUhdzKnMaikoE2MFBAsyS5XqExaEtFdfeouC6mAQ+MZ1dDQiK0OGZwMoFhyRaz1VguL3TJnc0ICgK/ORyckoIcS9/lHrRJCqWo7f1sJOrIoIkvGnKtacTIG8ONAeUxjvIPShTnuxiIa9Plq4TCMt3OttCeGKxOKbNDCK2JP6EXRwbBbaQzxRGshoJiRCnwf9h34mitNbD7SXyeUI2LPG1DRKQejJC5Vw0Yrt3qov9TJ2YNzF9blgiq9+87R+mCfxRF5zmlvjbbfc42FUIHfpdk2QR8hf+A5In8JderVeRObtxqWvI8QQG3u2B5vxYhXNftHiPhzko9yjzKeyVCZ4doqyzgAVjrJN5ebpbUnkAOWvefOdJloTZ3wcvkq3HzCBhMTASKiknD8SC8qMr2FSJog8fnRIgcS864HDHJk0qFOUyQ5yFFQPQvq3ZY7FpEAZxL7y+UsBcs8GmSlryXbfyym+0mP78ltjhxCJfyotd1XmQMAurqU6LM0hsX0llCoPd4GiZ0rpG3/LJBt+jpY5BYQSPDpc4EzaHD/bYBjfKGUgjb1MuJE6tw685yJwKBKCRI5IWPr3sSyXOCydCmaGG0kTrwZrnWo8XxhHOl8MGcvCoRrWFRotfx4JejPprK89f68D1T7mSE=
  template:
    metadata:
      name: backend-secret
      namespace: default
    type: Opaque
