---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBMSfdUv9n7SQmcF8crnEOiwLApuUWPD7T88GIFVmri4gEocX2DoN+RjrmW/Ars5xm+PgZQnOQB47C13e12AfunzZuRkoSkjcG7pTQuC8PnGgmox/f7OZswnwTh6VLll+x1kNmLt3wq/05qulXnrplL7Wsctfmmk1+kTMtDv+BvasYoyM51VTf9Vpc68G2J5iPLEnDuI+qMZk1nS8sSx/zYQs+8DLnowtmwuQOigKrtPq/+aeXr3PqYNDb6an5XwBShb2W3VlYG5vBRkUVEwqL4HkTNcT2LVLNu+PuH9ypb6GzhSgdT7dPTBugTX5AGZFh9NdWU0icQv/2GoRASrSb2wCJ4bi/18OfcVMSzWMfZ4Pd/5wpJnV6ijySCs5ziSt/QbhcMuVf9vgXJcd0iT9+61F9AXJuOr3SorgDn/pKj/BgF0fo0MWaHlvpuaEwg0C+6B2XfE8lSlD7ys9Y7lYCkKX3rvQHssLMrvWha2R+Ngdzu+rp0tjfDZPODJ2YJrnPEcVtD5Qk+Y4TGe9NvyfUhzEgpRZEfXaGX0IMOPR8QdLqMCr3s0Yg3K/3FlnCZsl49xb3B7X3MeCQOCIGCns4j10rNUjL2UrrmqCcYYF7/AgKKwJ5zkvPgEG6qFK0eOs+LHvRdA2vDqyDlwb72dk11CKAA+CGW3rgUI3ZTdrKnHHBtTL+yHaaLto6wt4pe4VUq869sp6zT2H8=
  template:
    metadata:
      name: postgres-secret
      namespace: default
    type: Opaque
