name: CI

on:
  pull_request:
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/ci.yml'

  push:
    branches: [main]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest


    permissions:
      contents: write
      packages: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Backend install
        working-directory: backend
        run: npm ci

      - name: Frontend install and build
        working-directory: frontend
        run: npm ci && npm run build

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build Docker images
        run: |
          docker build -t finance-api:${{ github.sha }} ./backend
          docker build -t finance-web:${{ github.sha }} ./frontend


      - name: Tag images for GHCR
        run: |
          docker tag finance-api:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/finance-devops-lab-api:${{ github.sha }}
          docker tag finance-web:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/finance-devops-lab-web:${{ github.sha }}

      - name: Push backend image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/finance-devops-lab-api:${{ github.sha }}



      - name: Push frontend image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/finance-devops-lab-web:${{ github.sha }}


      - name: Scan backend image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'finance-api:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Scan frontend image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'finance-web:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Update backend image tag
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          sed -i -E "s|(image: ghcr.io/${{ github.repository_owner }}/finance-devops-lab-api:).*|\1${IMAGE_TAG}|" k8s/backend.yaml

          echo "=== UPDATED IMAGE ==="
          grep -n "image:" k8s/backend.yaml

          echo
          echo "=== DIFF CHECK ==="
          git diff --check

          echo
          echo "=== DIFF ==="
          git diff -- k8s/backend.yaml

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add k8s/backend.yaml
          git commit -m "chore: update backend image to ${IMAGE_TAG}"
          git push origin HEAD:main
