name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest


    permissions:
      contents: read
      packages: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Backend install
        working-directory: backend
        run: npm ci

      - name: Frontend install and build
        working-directory: frontend
        run: npm ci && npm run build

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build Docker images
        run: |
          docker build -t finance-api:${{ github.sha }} ./backend
          docker build -t finance-web:${{ github.sha }} ./frontend


      - name: Tag images for GHCR
        run: |
          docker tag finance-api:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/finance-devops-lab-api:${{ github.sha }}
          docker tag finance-web:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/finance-devops-lab-web:${{ github.sha }}



      - name: Scan backend image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'finance-api:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Scan frontend image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'finance-web:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
